name: Enable Auto Merge

on:
  pull_request:
    types: [labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  enable-auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Enable PR automerge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GH_BOT_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
