name: Auto Merge
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
permissions:
  pull-requests: write
  contents: write
jobs:
  auto-merge:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'pull_request' }}
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ github.event.workflow_run.pull_requests[0].number }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Approve PR
        run: gh pr review $PR_NUMBER --approve
      - name: Enable auto-merge for PRs
        run: gh pr merge --merge --auto $PR_NUMBER
