name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, closed]

permissions:
  contents: write
  pull-requests: write
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.action != 'closed'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm install
      - run: npm run lint
      - run: npm run typecheck
      - run: npm run build

  test:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' || github.event.action != 'closed'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm install
      - run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]
    if: |
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && github.event.action == 'closed' &&
       github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main')
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm install
      - run: npm run build
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: web/dist
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GH_BOT_TOKEN }}
  auto-merge:
    runs-on: ubuntu-latest
    needs: [build, test]
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    steps:
      - name: Create GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
      - name: Approve PR
        run: gh pr review "$PR_URL" --approve
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          PR_URL: ${{ github.event.pull_request.html_url }}
      - name: Enable auto-merge
        run: gh pr merge --merge --auto "$PR_URL"
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          PR_URL: ${{ github.event.pull_request.html_url }}

